#!/usr/bin/env bash

BASE_URL=https://plugins.jetbrains.com/files
PLUGIN_DIR=/opt/idea/plugins
ZIP_FILE=/tmp/intellij-plugin.zip
PLUGIN_ID=$1
PLUGIN_UPDATE_ID=$2
PLUGIN_NAME=$3
PLUGIN_VERSION=$4

curl -fL "${BASE_URL}/${PLUGIN_ID}/${PLUGIN_UPDATE_ID}/${PLUGIN_NAME}-${PLUGIN_VERSION}.zip" -o ${ZIP_FILE} \
    && unzip ${ZIP_FILE} -d ${PLUGIN_DIR}
