#!/usr/bin/env bash

[[ -d /tmp/.X11-unix ]] && {
    DISPLAY=$DISPLAY
} || {
    DISPLAY=192.168.86.50:0
}

docker ps -q -f name=devenv-data || docker create --name=devenv-data devenv

docker run -it --rm \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v ~/src:/home/developer/src \
    -v ~/.ssh:/home/developer/.ssh \
    -v ~/.java:/home/developer/.java \
    -v ~/.m2:/home/developer/.m2 \
    -v $SSH_AUTH_SOCK:/tmp/ssh_auth_sock \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e SSH_AUTH_SOCK=/tmp/ssh_auth_sock \
    --volumes-from=devenv-data \
    --name=devenv \
    --network=host \
    devenv
