#!/usr/bin/env bash

CONTAINER_NAME=${1-devenv}

[[ $DISPLAY == *org.macosforge.xquartz* ]] && {
    DISPLAY=$(ifconfig en0 | grep -P inet\ | cut -d' ' -f2):0
} || {
    DISPLAY=$DISPLAY
}

[[ $(docker ps -aq -f name=devenv-data) == "" ]] && { echo "Creating data container..." && docker create --name=devenv-data devenv; }

docker run -it --rm \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v ~/src:/home/developer/src \
    -v ~/.ssh:/home/developer/.ssh \
    -v ~/.java:/home/developer/.java \
    -v ~/.m2:/home/developer/.m2 \
    -v $SSH_AUTH_SOCK:/tmp/ssh_auth_sock \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e SSH_AUTH_SOCK=/tmp/ssh_auth_sock \
    --volumes-from=devenv-data \
    --name=${CONTAINER_NAME} \
    --network=host \
    --security-opt=seccomp:unconfined \
    devenv
